Check for libpthread in SConstruct
Resolves linkage issue:

Linking build/release/rlvmTests ...
/usr/bin/ld: build/release/test/graphics_object_test.o: undefined reference to
symbol 'pthread_getspecific@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_getspecific@@GLIBC_2.2.5' is defined in DSO
/lib64/libpthread.so.0 so try adding it to the linker command line
/lib64/libpthread.so.0: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
scons: *** [build/release/rlvmTests] Error 1
scons: building terminated because of errors.

Signed-off-by: Marek Vasut <marek.vasut@gmail.com>
Signed-off-by: Elliot Glaysher <glaysher@umich.edu>